### ISSUE TITLE
Stashing no longer works

### ISSUE THREAD

**Issue by mkalinski** [l10nelw/winger#36]
It stopped working after the last update 2.4.1. Was working in 2.4.0.

Figures I'm the one to file a mirror issue to #15 :sweat_smile: 

1. Open new window.
2. Open some tab in it.
3. Go to Winger panel and type `/stash{Enter}`.
4. The window closes, but no folder or bookmarks are created under the Stashed Windows folder.

I looked at `about:devtools-toolbox?id=winman%40lionelw&type=extension` and there was no logs.

My system is Fedora 38, my desktop environment is Gnome 44 on Wayland.

**Comment by l10nelw** [comment]
Apologies and thank you! The fix is coming very shortly.

**Comment by loopernow** [comment]
I'm not sure what the correct thing to do is if this issue is occurring again (comment here or open a new issue?).

I've just started using Winger 2.4.3 and I enabled stashing and tried it out. What it has done is it has created the Stashed Windows folder in the specified location. But when I invoke the /stash command, the same thing occurs as described in step 4 by the OP--the window closes but no folder of bookmarks is created.

I'm on Windows 10.
