### ISSUE TITLE
Blank window names in Winger

### ISSUE THREAD

**Issue by ppatel-gh** [l10nelw/winger#41]
I have recently run into an issue where the names of the windows are blank in Winger list, however, if I hover my mouse over a window I can see the window's name in the tooltip. I am running FireFox version 124.0.1 (64-bit), Mac OS version Sonoma 14.4 (23E214), M1 Pro. I have tried disabling and re-enabling winger extension, and uninstalling and re-installing it, but the issue remains.

![Screenshot 2024-03-26 at 2 06 12 PM](https://github.com/l10nelw/winger/assets/93221728/b1f717ff-d015-420b-83c3-00e65c9104c8)

**Comment by l10nelw** [comment]
I haven't been able to reproduce this problem. Is it still happening and do you have any more clues to why?

**Comment by ppatel-gh** [comment]
> I haven't been able to reproduce this problem. Is it still happening and do you have any more clues to why?

yeah it's still happening, I am not sure what's causing it, just as a FYI I also use this extension called [Window Titler](https://addons.mozilla.org/en-US/firefox/addon/window-titler/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search) to give custom titles to my windows, I wonder if that has any bearing to this issue.

**Comment by l10nelw** [comment]
Now we're getting somewhere. Do you need Window Titler, or would Winger alone meet your window naming needs? They conflict, so please either disable/remove Window Titler or [follow these instructions](https://github.com/l10nelw/winger/wiki/Using-Winger-with-another-window-naming-extension).

**Comment by Alucquere** [comment]
I tried removing All Tabs Helper and Tab Manager Plus, and that didn't help.

I did notice that Tab Manager Plus still has a button but doesn't work properly, so, maybe there's a problem with Firefox that's affecting both Tab Manager Plus and Winger.

**Comment by ppatel-gh** [comment]
> Now we're getting somewhere. Do you need Window Titler, or would Winger alone meet your window naming needs? They conflict, so try either disable/remove Window Titler or [follow these instructions](https://github.com/l10nelw/winger/wiki/Using-Winger-with-another-window-naming-extension). Let me know how it goes.

I removed Window Titler, and followed the instructions for the Winger settings, still the issue remains, is it possible to reset Winger in some way?

**Comment by l10nelw** [comment]
Please do the following:
1. Open the panel and enter `/debug` (you won't see anything happen)
2. Open a tab and go to `about:devtools-toolbox?id=winman@lionelw&type=extension`
3. Click on Console (next to Inspector)
4. Enter `await Winfo.getAll(['titleSansName'])`
5. Click on the arrow next to "Array"

You should see a list of Objects each with givenName and titleSansName, containing text you would expect from your windows. They should not be blank. Let me know what you see.

**Comment by l10nelw** [comment]
Please do the following:
1. Open the panel and enter `/debug` (you won't see anything happen)
2. Open a tab and go to `about:devtools-toolbox?id=winman@lionelw&type=extension`
3. Click on Console (next to Inspector)
4. Enter `await Winfo.getAll(['titleSansName'])`
5. Click on the arrow next to the "Array" output

You should see a list of Objects each with givenName and titleSansName, containing text you would expect from your windows. They should not be blank. Let me know what you see.

**Comment by Alucquere** [comment]
Sorry it took me so long to see this. 
I did this. I don’t see window names, because I haven’t had a chance to name the windows, but I see the titles of the selected tabs in each window. So, I see what Winger is using as the name. 
I think the big problem is that I can’t name the windows. 
The names are a
Sent from Yahoo Mail for iPhone


On Monday, April 22, 2024, 9:17 AM, Lionel Wong ***@***.***> wrote:




Please do the following:
   
   - Open the panel and enter /debug (you won't see anything happen)
   - Open a tab and go to ***@***.***&type=extension
   - Click on Console (next to Inspector)
   - Enter await Winfo.getAll(['titleSansName'])
   - Click on the arrow next to the "Array" output

You should see a list of Objects each with givenName and titleSansName, containing text you would expect from your windows. They should not be blank. Let me know what you see.
