### ISSUE TITLE
[Feature Request] Stash to the top of home folder

### ISSUE THREAD

**Issue by sonbua** [l10nelw/winger#44]
Thank you for your work on such a great addon. I'm very happy that I finally find it.

For those who stash windows often, and there are a handful of stashed windows in the home folder, it would be easier to unstash the recently stashed windows at a later time if they are placed at the top of the folder. As of now, one has to scroll through the folder to the end to find the recent windows to unstash.

Another good example would be one, who set the root folder to be the Bookmarks Toolbar, and without subfolder being set. She could conveniently unstash a recent window from the Bookmarks Toolbar, or in the Bookmarks sidebar.

It would be convenient for these audiences to have an option to stash windows to the top the the home folder.

I think this is also the behavior of Tab Stash.

Relates to #24

**Comment by l10nelw** [comment]
Done! v2.7.0

**Comment by sonbua** [comment]
That's awesome!

**Comment by BenceSzalai** [comment]
So is this optional? I'm so used to having the new Stashed Windows at the bottom, it is a lot of friction that it suddenly started to add them at the beginning. I agree it is objectively better for new users, but now my stashed windows are in an ACS order by date, but new ones are started to be added in a DESC at the beginning, which is just chaos. I'll probably at some point reverse my old stashes to DESC order, as it seems more convenient, but to manually reverse my long list of windows at the moment seem daunting. For the time it'd be good to stick to old behaviour.

**Comment by sonbua** [comment]
> It would be convenient for these audiences to have an option to stash windows to the top the the home folder.

AFAIK, it's the default behavior with v2.7.0, and there is no ASC/DESC option yet.

**Comment by l10nelw** [comment]
Hey @BenceSzalai, sorry for not coming back to your issue sooner, might even be far too late. I found some [bookmark sorting extensions](https://addons.mozilla.org/en-US/firefox/search/?q=sort%20bookmarks) to help you get everything in descending order.

**Comment by BenceSzalai** [comment]
No, not too late. I'll use Winger as long as it exists. One of the best thing that happened to my Browsing experience ever!

Interesting idea to use some other plugins to force a certain sorting order. I think it'll not be my solution, because I am actually manually reordering them sometimes, so I want those changes to be kept, only that I preferred the new ones to be added where I was used to it.

So there is a difference between enforcing a certain order vs adding new items to the end/beginning of the list. Of course I did not explain it so far, so thank you for the suggestion anyway!

**Comment by l10nelw** [comment]
Oh what I meant by "too late" was you might have already long figured something out by yourself (like looking up bookmark sorting tools) 😄
